# Generated by Django 4.2.2 on 2023-06-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='user_picture',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
