# Generated by Django 4.1 on 2023-05-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='subject',
            new_name='title',
        ),
    ]
