# Generated by Django 4.1 on 2023-06-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
