# Generated by Django 4.1 on 2023-06-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
