# Generated by Django 4.1 on 2023-05-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_first_name_remove_order_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_line_1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_line_2',
            new_name='address_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.AddField(
            model_name='order',
            name='zip',
            field=models.IntegerField(null=True),
        ),
    ]
