# Generated by Django 4.1 on 2023-05-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_grand_total_alter_order_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gift_charge',
            field=models.FloatField(null=True),
        ),
    ]
