# Generated by Django 4.1 on 2023-05-21 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='gift',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
