# Generated by Django 4.1 on 2023-05-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_variation_variation_value'),
        ('order', '0008_remove_orderproduct_gift_remove_orderproduct_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='variations',
            field=models.ManyToManyField(blank=True, to='product.variation'),
        ),
    ]
