# Generated by Django 4.1 on 2023-05-21 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_orderproduct_variation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_total',
            new_name='total',
        ),
    ]
