# Generated by Django 4.1 on 2023-05-21 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_rename_order_total_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_note',
            new_name='note',
        ),
    ]
