# Generated by Django 4.1 on 2023-05-21 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_rename_order_note_order_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='gift_charge',
            new_name='gift_charges',
        ),
    ]
