# Generated by Django 4.1 on 2023-05-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_awb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('In Return', 'In Return'), ('Refunded', 'Refunded'), ('Completed', 'Completed')], default='New', max_length=20),
        ),
    ]
